/*------------------------------------------------------------------*-

   SPI_x25.H (v1.00)

  ------------------------------------------------------------------

   - See SPI_x25.C for details.


   COPYRIGHT
   ---------

   This code is from the book:

   PATTERNS FOR TIME-TRIGGERED EMBEDDED SYSTEMS by Michael J. Pont 
   [Pearson Education, 2001; ISBN: 0-201-33138-1].

   This code is copyright (c) 2001 by Michael J. Pont.
 
   See book for copyright details and other information.

-*------------------------------------------------------------------*/

#include "Main.h"

// ------ Public function prototypes -------------------------------

void SPI_X25_Write_Byte(const tWord, const tByte);
tByte SPI_X25_Read_Byte(const tWord);

/*------------------------------------------------------------------*-
  ---- END OF FILE -------------------------------------------------
-*------------------------------------------------------------------*/


